### ISSUE TITLE
Can't get subtitles for FA language

### ISSUE THREAD

**Issue by msfoxofficial** [RafayGhafoor/Subscene-Subtitle-Grabber#10]
I can't get subtitles for FA (farsi_persian) language.
For example, you can test it with 
subgrab -m "Weathering with You" -l FA

**Comment by RafayGhafoor** [comment]
@msfoxofficial, Thanks, it was a bug in detecting language context which has been fixed now in the latest release (v1.0.4). Please upgrade your package to latest version and it should work :) (`pip install --user subgrab -U`)

**Comment by msfoxofficial** [comment]
Thank you, it is working.
