### ISSUE TITLE
seems the search result does not show exact, close and tv series section of subscene.com

### ISSUE THREAD

**Issue by msfoxofficial** [RafayGhafoor/Subscene-Subtitle-Grabber#11]
Please compare your result with subscene.com.
subgrab -m joker or subgrab -m joker 2019
It seems your script just shows the popular result of subscene.com. By the way, if subscene.com shows the movie in the exact section, so your script will miss it.

**Comment by RafayGhafoor** [comment]
@msfoxofficial, It is the intended behavior to search media name in popular section as a priority and if not found in the given i.e., popular section, it searches in other sections.

In this case, it might be the fault of subscene provider as Joker 2019 is popular which is not shown in the popular section. An enhancement would be to provide the user with complete details section-wise as displayed on the website.
