### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Subgrab'

### ISSUE THREAD

**Issue by ialqwaiz** [RafayGhafoor/Subscene-Subtitle-Grabber#12]
`
root@omvpi:/media# subgrab
Traceback (most recent call last):
  File "/usr/local/bin/subgrab", line 5, in <module>
    from subgrab.cli import main
  File "/usr/local/lib/python3.8/site-packages/subgrab/cli.py", line 23, in <module>
    os.mkdir(log_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Subgrab'

`

**Comment by RafayGhafoor** [comment]
Please try doing this:

```bash
mkdir -p /root/.local/share && subgrab
```

**Comment by ialqwaiz** [comment]
> Please try doing this:
> 
> ```shell
> mkdir -p /root/.local/share && subgrab
> ```

It works after manually creating the directories... the code cannot create these directories for some reason..

**Comment by RafayGhafoor** [comment]
@ialqwaiz, change line 23 of 
"/usr/local/lib/python3.8/site-packages/subgrab/cli.py" 
to this:
`os.makedirs(log_directory, exist_ok=True)`

P.s. the new release will have the fix.

**Comment by ialqwaiz** [comment]
> @ialqwaiz, change line 23 of
> "/usr/local/lib/python3.8/site-packages/subgrab/cli.py"
> to this:
> `os.makedirs(log_directory, exist_ok=True)`
> 
> P.s. the new release will have the fix.

this works...
