### ISSUE TITLE
subtitle language

### ISSUE THREAD

**Issue by ialqwaiz** [RafayGhafoor/Subscene-Subtitle-Grabber#13]
Hi,
hope to see the new release soon :)

I chose the arabic language but the downloaded subtitle files are in english...
The command is as follows
`subgrab -d /media/Legion/Season.1/Legion.S01E01.720p.HDTV.x265.ShAaNiG/ -l ar`

**Comment by RafayGhafoor** [comment]
Only, "Dutch, English, French, Italian, Polski, Portuguese (Brazil), Romanian, Spanish, Swedish and Turkish" languages are available from subdb.com. As allsubdb API is used for directory (-d) parameter, as mentioned [here](https://github.com/RafayGhafoor/Subscene-Subtitle-Grabber#providers-supported).
