### ISSUE TITLE
KeyError: 'FR' issue

### ISSUE THREAD

**Issue by hista** [RafayGhafoor/Subscene-Subtitle-Grabber#15]
Hi, I've run this command, which generate an error message, could you please tell me how to fix it?

```
subgrab -l FR
Traceback (most recent call last):
  File "/home/hista/.local/bin/subgrab", line 10, in <module>
    sys.exit(main())
  File "/home/hista/.local/lib/python2.7/site-packages/subgrab/SubGrab.py", line 73, in main
    subscene.DEFAULT_LANG = subscene.LANGUAGE[args.lang.upper()]
KeyError: 'FR'
```

**Comment by RafayGhafoor** [comment]
@hista, French is not supported.

The languages currently supported by the subscene provider are:

- Arabic
- Burmese
- Danish
- Dutch
- English
- Farsi/Persian
- Indonesian
- Italian
- Malay
- Spanish
- Vietnamese
