### ISSUE TITLE
Difference to other solutions

### ISSUE THREAD

**Issue by eikaramba** [RafayGhafoor/Subscene-Subtitle-Grabber#2]
Hey there, thank you for this project. Always looking forward to see something like that. However i wanted to ask if you know https://github.com/Diaoul/subliminal or https://github.com/caronc/nzbget-subliminal and what specifially your library can provide what they can't ?

**Comment by RafayGhafoor** [comment]
Yeah @eikaramba, I have seen the subliminal project. The difference that is noticeable in the both libraries is that subliminal doesn't support site subscene (which i use mostly for downloading subtitles) - it also has a cli mode that allows you to select title (if corresponding title not found), download subtitles without the existence of media file. This prevents the use of other libraries i.e, enzyme for detecting metadata and making it more lightweight. It will add support for the site yts subtitles and other apis (which might also be present in subliminal).
