### ISSUE TITLE
[Feature request]: python3 support

### ISSUE THREAD

**Issue by lgbaldoni** [RafayGhafoor/Subscene-Subtitle-Grabber#3]
It would be nice to have it. 2to3 fixes a few minor things, but I'm not sure both original intent
and py2 compatibility are kept.

**Comment by RafayGhafoor** [comment]
@luigino, It will be ported to python 3 in the next version.

**Comment by lgbaldoni** [comment]
Great, thanks.

**Comment by RafayGhafoor** [comment]
@luigino, Please head to developer branch - the code has been ported to python 3 for now. I have to write tests for releasing new version to ensure that it works for both python version 2 and 3. As i am busy, i can't promise when the new version will be released. To use it with python 3, follow the below procedure:

```
git clone https://github.com/RafayGhafoor/Subscene-Subtitle-Grabber -b dev && cd Subscene-Subtitle-Grabber

python setup.py install
```

**Comment by lgbaldoni** [comment]
Thanks, it appears to be working. Will wait for the official release though.

**Comment by RafayGhafoor** [comment]
@luigino, the script has been ported to python 3 :)

**Comment by lgbaldoni** [comment]
:thumbsup:
