### ISSUE TITLE
Does NOT work on Linux

### ISSUE THREAD

**Issue by msfoxofficial** [RafayGhafoor/Subscene-Subtitle-Grabber#9]
Hi there!
when I try to call your package, I got this:
>>> subgrab -m Doctor Strange
  File "<stdin>", line 1
    subgrab -m Doctor Strange
               ^
SyntaxError: invalid syntax

**Comment by RafayGhafoor** [comment]
Hi @msfoxofficial,

Which version of python are you using?

**Comment by msfoxofficial** [comment]
> Hi @msfoxofficial,
> 
> Which version of python are you using?

3.8

**Comment by RafayGhafoor** [comment]
Can you confirm whether you are running subgrab command on the terminal or via interpreter?

![image](https://user-images.githubusercontent.com/20343475/82980388-cabd3e00-a002-11ea-89c3-cd63e3686ba2.png)

**Comment by msfoxofficial** [comment]
Thank you. Just adding the installed directory to PATH resolved the problem.
export PATH=/home/<user>/.local/bin
